import pandas as pd

data = pd.read_csv("imdb_top_list.csv")
print(data)
df = pd.DataFrame(data)
print(df)
print(df.columns)
result = df.head()
print(result)
result = df.head(10)
print(result)
result = df.tail()
print(result)
result = df.tail(10)
print(result)
result = df["Title"].head()
print(result)
result = df[5:20][["Title","Rate"]].head()
print(result)
result = df[df["Rate"]>8.0][["Title","Rate","Duration"]].head(50)
print(result)
result = df[ (df["Rate"]<9.0) | (df["Metascore"]>90) ][["Title","Rate","Metascore"]].head(30)
print(result)
